spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: cart-order-service
          uri: lb://CART-ORDER-SERVICE
          predicates:
            - Path=/cart/**, /order/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka